version: '3.1'
services:
    api:
      build: .
      depends_on:
        - postgres
      restart: always
      ports:
        - "3000:3000"
      environment:
        - "DB_USER=postgres"
        - "DB_HOST=postgres"
        - "DB_DB=mydb"
        - "DB_PASSWORD=12345678"
        - "DB_PORT=5432"
    postgres:
      image: postgres:10.11
      environment:
        - "POSTGRES_PASSWORD=12345678"
      ports:
        - "5432:5432"
      volumes:
        - ./init.sql:/docker-entrypoint-initdb.d/init.sql
